import { useMemo, useState } from "react";
import DataTable from "@/components/DataTable";
import DeleteButton from "@/components/DeleteButton";
import FormCard from "@/components/FormCard";
import { InputField, Label, SelectField } from "@/components/FormControls";
import SectionGrid from "@/components/SectionGrid";
import { useMasterData } from "@/hooks/useMasterData";
import api from "@/shared/api";

export default function LoadsPage() {
  const { data, refresh } = useMasterData();
  const [form, setForm] = useState({ subjectId: data.subjects[0]?.id ?? "", groupId: data.groups[0]?.id ?? "", teacherId: data.teachers[0]?.id ?? "", lessonType: "lecture", weeklyLessons: "1", preferredBuildingId: "" });
  const [loading, setLoading] = useState(false);
  const subjectMap = useMemo(() => new Map(data.subjects.map((item) => [item.id, item.name])), [data.subjects]);
  const groupMap = useMemo(() => new Map(data.groups.map((item) => [item.id, item.name])), [data.groups]);
  const teacherMap = useMemo(() => new Map(data.teachers.map((item) => [item.id, item.fullName])), [data.teachers]);
  const buildingMap = useMemo(() => new Map(data.buildings.map((item) => [item.id, `${item.code} - ${item.name}`])), [data.buildings]);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { await api.post("/masterdata/loads", form); setForm({ subjectId: data.subjects[0]?.id ?? "", groupId: data.groups[0]?.id ?? "", teacherId: data.teachers[0]?.id ?? "", lessonType: "lecture", weeklyLessons: "1", preferredBuildingId: "" }); await refresh(); } finally { setLoading(false); } };
  const remove = async (id: string) => { await api.delete(`/masterdata/loads/${id}`); await refresh(); };
  return <SectionGrid><FormCard title="Yuklama qo‘shish" description="Fan, guruh, ustoz, dars turi va afzal binoni biriktiring."><form className="space-y-4" onSubmit={submit}><Label title="Fan"><SelectField value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })}>{data.subjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField></Label><Label title="Guruh"><SelectField value={form.groupId} onChange={(e) => setForm({ ...form, groupId: e.target.value })}>{data.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField></Label><Label title="Ustoz"><SelectField value={form.teacherId} onChange={(e) => setForm({ ...form, teacherId: e.target.value })}>{data.teachers.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</SelectField></Label><div className="grid gap-4 sm:grid-cols-2"><Label title="Dars turi"><SelectField value={form.lessonType} onChange={(e) => setForm({ ...form, lessonType: e.target.value })}><option value="lecture">lecture</option><option value="seminar">seminar</option><option value="lab">lab</option><option value="computer_lab">computer_lab</option></SelectField></Label><Label title="Haftalik son"><InputField type="number" value={form.weeklyLessons} onChange={(e) => setForm({ ...form, weeklyLessons: e.target.value })} /></Label></div><Label title="Afzal bino"><SelectField value={form.preferredBuildingId} onChange={(e) => setForm({ ...form, preferredBuildingId: e.target.value })}><option value="">Tanlanmagan</option>{data.buildings.map((item) => <option key={item.id} value={item.id}>{item.code} - {item.name}</option>)}</SelectField></Label><button disabled={loading || !data.subjects.length || !data.groups.length || !data.teachers.length} className="rounded-2xl bg-brand-700 px-5 py-3 text-sm font-semibold text-white">{loading ? "Saqlanmoqda..." : "Qo‘shish"}</button></form></FormCard><DataTable title="Yuklamalar ro‘yxati" data={data.loads} columns={[{ key: "subjectId", title: "Fan", render: (item) => subjectMap.get(item.subjectId) ?? item.subjectId }, { key: "groupId", title: "Guruh", render: (item) => groupMap.get(item.groupId) ?? item.groupId }, { key: "teacherId", title: "Ustoz", render: (item) => teacherMap.get(item.teacherId) ?? item.teacherId }, { key: "lessonType", title: "Turi" }, { key: "weeklyLessons", title: "Haftasiga" }, { key: "preferredBuildingId", title: "Afzal bino", render: (item) => item.preferredBuildingId ? (buildingMap.get(item.preferredBuildingId) ?? item.preferredBuildingId) : "-" }, { key: "actions", title: "Amal", render: (item) => <DeleteButton onClick={() => remove(item.id)} /> }]} /></SectionGrid>;
}
